# Site settings
title: "梵道流"
description: "继往圣之绝学"
url: "https://www.fandaoliu.com" # Your custom domain
github_username: "gptapplied"
repository: gptapplied/fandaoliu-knowledge
lang: zh-CN

# Build settings
remote_theme: pages-themes/cayman@v0.2.0

# Default values - apply to all md files
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"