# Site settings
title: "梵道流"
description: "一个基于「梵道流」理论的跨学科知识探索平台"
url: "https://www.fandaoliu.com" # Your custom domain
github_username: "gptapplied"
repository: gptapplied/fandaoliu-knowledge

# Build settings
remote_theme: pages-themes/cayman@v0.2.0

# Default values - apply to all md files
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"